const INSERT_QUESTION = 'INSERT_QUESTION'
const UPDATE_QUESTION = 'UPDATE_QUESTION'
const DELETE_QUESTION = 'DELETE_QUESTION'
const INITIALIZE_TEST = 'INITIALIZE_TEST'

const GET_PROBLEM = 'GET_PROBLEM'
const ADD_PROBLEM = 'ADD_PROBLEM'
const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
const UPDATE_PROBLEMS = 'UPDATE_PROBLEMS'
const GET_PROBLEMS = 'GET_PROBLEMS'
const DELETE_PROBLEM = 'DELETE_PROBLEM'
const INITIALIZE_PROBLEMS = 'INITIALIZE_PROBLEMS'
const PROBLEM_LOADING = 'PROBLEM_LOADING'

const GET_TESTS = 'GET_TESTS'
const DELETE_TEST = 'DELETE_TEST'
const TEST_LOADING = 'TEST_LOADING'

export {
  INSERT_QUESTION,
  UPDATE_QUESTION,
  DELETE_QUESTION,
  INITIALIZE_TEST,
  GET_PROBLEM,
  ADD_PROBLEM,
  UPDATE_PROBLEM,
  UPDATE_PROBLEMS,
  DELETE_PROBLEM,
  GET_PROBLEMS,
  INITIALIZE_PROBLEMS,
  PROBLEM_LOADING,
  GET_TESTS,
  DELETE_TEST,
  TEST_LOADING
}