const INSERT_QUESTION_TITLE = 'INSERT_QUESTION_TITLE'
const INSERT_QUESTION_IMAGE = 'INSERT_QUESTION_IMAGE'
const INSERT_QUESTION_CHOICES = 'INSERT_QUESTION_CHOICES'
const INSERT_QUESTION_ANSWER = 'INSERT_QUESTION_ANSWER'
const INSERT_QUESTION_TEMA = 'INSERT_QUESTION_TEMA'
const INSERT_QUESTION_CATEGORY = 'INSERT_QUESTION_CATEGORY'
const INSERT_QUESTION_DIFFICULTY = 'INSERT_QUESTION_DIFFICULTY'
const INSERT_QUESTION_VIDEO = 'INSERT_QUESTION_VIDEO'
const INSERT_QUESTION = 'INSERT_QUESTION'
const UPDATE_QUESTION = 'UPDATE_QUESTION'
const DELETE_QUESTION = 'DELETE_QUESTION'
const INITIALIZE_TEST = 'INITIALIZE_TEST'

export {
  INSERT_QUESTION_TITLE,
  INSERT_QUESTION_IMAGE,
  INSERT_QUESTION_CHOICES,
  INSERT_QUESTION_ANSWER,
  INSERT_QUESTION_TEMA,
  INSERT_QUESTION_CATEGORY,
  INSERT_QUESTION_DIFFICULTY,
  INSERT_QUESTION_VIDEO,
  INSERT_QUESTION,
  UPDATE_QUESTION,
  DELETE_QUESTION,
  INITIALIZE_TEST,
}