const INSERT_QUESTION = 'INSERT_QUESTION'
const UPDATE_QUESTION = 'UPDATE_QUESTION'
const DELETE_QUESTION = 'DELETE_QUESTION'
const INITIALIZE_TEST = 'INITIALIZE_TEST'
const LOADING = 'LOADING'

const GET_TESTS = 'GET_TESTS'
const GET_QUESTIONS = 'GET_QUESTIONS'
const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS'
const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS'
const CLEAR_TESTS = 'CLEAR_TESTS'

export {
  INSERT_QUESTION,
  UPDATE_QUESTION,
  DELETE_QUESTION,
  INITIALIZE_TEST,
  LOADING,
  GET_TESTS,
  GET_QUESTIONS,
  UPDATE_QUESTIONS,
  CLEAR_QUESTIONS,
  CLEAR_TESTS,
}